### ISSUE TITLE
Support for GHC-8.8

### ISSUE THREAD

**Issue by sjakobi** [diagrams/diagrams-svg#114]
As far as I can tell, this is currently only blocked on

* `svg-builder`, which https://github.com/diagrams/svg-builder/pull/10 takes care of

and

* `diagrams-lib`, for which there is https://github.com/diagrams/diagrams-lib/pull/343 which needs to be improved though AFAICT.

**Comment by sjakobi** [comment]
@byorgey Now that `svg-builder` and `diagrams-lib` are compatible, could you also make a release or revision for `diagrams-svg`?

**Comment by byorgey** [comment]
@sjakobi Yes, coming very soon!  As soon as it [passes CI](https://travis-ci.org/diagrams/diagrams-svg) ...

**Comment by byorgey** [comment]
Finally got everything squared away.  `diagrams-svg-1.4.3` is now on Hackage.

**Comment by sjakobi** [comment]
Thanks a lot @byorgey! :)
