### ISSUE TITLE
clipping broken

### ISSUE THREAD

**Issue by claudeha** [diagrams/diagrams-svg#70]
Tested with diagrams-svg-1.1.0.4, test case:

    import Diagrams.Prelude
    import Diagrams.Backend.SVG.CmdLine (defaultMain)
    -- import Diagrams.Backend.Cairo.CmdLine (defaultMain)
    
    clipBy' p d = d # clipBy p # withEnvelope p
    
    shape c = square 2 # fc c # clipBy' (circle 0.5)
    
    main = defaultMain $
      ((shape red  ||| shape yellow)
       ===
       (shape blue ||| shape green)
      ) # bg white

Correct output with cairo backend, using -w 1024 -o bug.svg:
![clipping-bug-cairo-backend](https://cloud.githubusercontent.com/assets/10728495/6098747/1200e7f8-afe0-11e4-8036-45e87a316b3d.png)

Bad output with svg backend, using -w 1024 -o bug.svg:
![clipping-bug-svg-backend](https://cloud.githubusercontent.com/assets/10728495/6098748/12040564-afe0-11e4-8491-ce14a88863bb.png)

SVG converted to PNG using rsvg -w 128 bug.svg -o bug.png

    $ rsvg --version
    rsvg-convert version 2.36.1

**Comment by cchalmers** [comment]
The problem is we're defining the clip path inside in the group that's being clipped:

```svg
<g clip-path="url(#clipmyClip1)">
  <clipPath id="clipmyClip1">
    <path d="CIRCLE_PATH"/>
  </clipPath>
  <g fill-opacity="1.0" fill="rgb(0,128,0)">
    <g fill-opacity="1.0" fill="rgb(0,128,0)">
      <path d="SQUARE_PATH"/>
    </g>
  </g>
</g>
```

It seems that not all renders can handle this. Moving the clip definition outside the group seems to fix it:

```svg
<clipPath id="clipmyClip1">
  <path d="CIRCLE_PATH"/>
</clipPath>
<g clip-path="url(#clipmyClip1)">
  <g fill-opacity="1.0" fill="rgb(0,128,0)">
    <g fill-opacity="1.0" fill="rgb(0,128,0)">
      <path d="SQUARE_PATH"/>
    </g>
  </g>
</g>
```

Also looks like we have a redundant ` <g fill-opacity="1.0" fill="rgb(0,128,0)">`, would be nice if we could get rid of these.

**Comment by jeffreyrosenbluth** [comment]
This should be relatively easy to fix if it is in fact a simple matter of moving the definition out of the group. I wonder more broadly if we should put all definintions (clip paths, gradients, fonts, etc) in a defs tag?

**Comment by cchalmers** [comment]
It looks like it's the recommended way of doing it so I guess we should.
