### ISSUE TITLE
Embedded font definitions

### ISSUE THREAD

**Issue by acowley** [diagrams/diagrams-svg#78]
I'm trying to update `Chart-diagrams` to `diagrams-svg-1.3`, but I'm not sure how to deal with embedded font definitions. Previously, `SVGFonts` was used to produce some markup that was passed to the `SVGOptions` record via its second parameter. That parameter is now a list of `Attribute`s. Is there a way to go from the output of [makeSvgFont](http://hackage.haskell.org/package/SVGFonts-1.5.0.0/docs/Graphics-SVGFonts-WriteFont.html) to something I can stuff into a value of type `[Attribute]`?

**Comment by acowley** [comment]
To be very transparent, this is the [line](https://github.com/acowley/haskell-chart/blob/Fix80/chart-diagrams/Graphics/Rendering/Chart/Backend/Diagrams.hs#L224) I don't know how to port.

**Comment by jeffreyrosenbluth** [comment]
Yes I think this was an oversight. Thanks for pointing it out.
The questions is how to fix it.
I'll have a look tomorrow.

**Comment by jeffreyrosenbluth** [comment]
@acowley I think this branch  https://github.com/diagrams/diagrams-svg/pull/79
should allow you to finish updating to 1.3.
Can you see if these changes are adequate? I would still need to write a hasahable
instance for `Html ()` from Chis Done's `Lucid` package which would mean sending a 
pull request to Chris, he's been very accommodating in the past so I don't foresee this would be
problem.

**Comment by acowley** [comment]
I've built everything I do have, and everything works, but I don't knowingly have a test case that exercises the font embedding.

**Comment by jeffreyrosenbluth** [comment]
Thanks for testing. Give me a  day or two to fix the documentation and the migration guide and i'll merge this branch and push it up to hackage.

**Comment by jeffreyrosenbluth** [comment]
The new version 1.3.1 is up on hackage

**Comment by acowley** [comment]
Thanks so much! I've opened the PR on `Chart-diagrams`, so hopefully that can be updated soon.
