### ISSUE TITLE
Applying SVG Attribute via SVGOptions' _svgDefinitions Fails

### ISSUE THREAD

**Issue by rlehquinn** [diagrams/diagrams-svg#84]
I'm trying to use renderPretty' with SVGOptions to apply the SVG attribute "xMinYMin" via _svgDefinitions. 
It fails in version 1.3.1.4 due to a change to 'Maybe SvgM'

**Comment by jeffreyrosenbluth** [comment]
@rlehquinn 

you can try using this branch
of diagrams-svg
 https://github.com/diagrams/diagrams-svg/tree/svg-options
with the following code
```
import qualified Data.Text as T
import qualified Lucid.Svg as LST
import Diagrams.Prelude
import Diagrams.Backend.SVG

svgOpt = SVGOptions {
  _size = (mkSizeSpec $ V2 (Just 400) (Just 400)),
  _idPrefix = T.pack "bla",
  _svgDefinitions = Nothing,
  _moreOptions = [(LST.preserveAspectRatio_ $ T.pack "xMinYMin")],
  _generateDoctype = True
}
```

let me know if this does what you need.

**Comment by jeffreyrosenbluth** [comment]
See: https://github.com/diagrams/diagrams-svg/commit/11041495a19a107c1782d78a32ffd326fe9d09a7
